start = expression

expression
    = group
    / quote
    / atom
    / empty { return []; }

group     = empty* oparen expr:expression+ cparen { return expr; }
quote     = empty* "'"    expr:expression         { return ["quote", expr]; }
atom      = empty*        chars:validchar+ empty* { return chars.join(""); }

empty     = comment / ws
comment   = ";;" [^\n]* ws?
ws        = [ \t\r\n]+ comment?

validchar = [0-9a-zA-Z_?!+\-=@#$%^&*/.]
oparen    = "(" empty*
cparen    = ")" empty*
